CREATE TABLE users (
id SERIAL PRIMARY KEY,
name TEXT NOT NULL,
email TEXT UNIQUE NOT NULL,
password TEXT NOT NULL,
"createdAt" TIMESTAMP DEFAULT NOW()
);

CREATE TABLE sessions (
    id SERIAL PRIMARY KEY,
token TEXT NOT NULL UNIQUE,
"userId" INTEGER NOT NULL REFERENCES users(id),
"createdAt" TIMESTAMP DEFAULT NOW()
);

CREATE TABLE ranking (
    id SERIAL PRIMARY KEY,
url TEXT NOT NULL,
"visiURL" INTEGER NOT NULL DEFAULT 0,
"shorUrl" TEXT NOT NULL,
"userId" INTEGER NOT NULL REFERENCES users(id),
"createdAt" TIMESTAMP DEFAULT NOW()
);